# -*- coding: utf-8 -*-
"""Funciones básicas de python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUBeMaSmA6TMba__QYfQyYvmWVRImMI8
"""

print("hola")

nombre = input("ingrese su nombre")
print(nombre)

type(10)

type(nombre)

len(nombre)

numero = int(input("ingrese un numero"))
print(numero)
print(type(numero))

for n in range(5):
  print(n)

frutas = ["manzana", "pera", "uva"]
for fruta in frutas:
  print(fruta)

for i, fruta in enumerate(frutas):
  print(i, fruta)

nombres = ["Ana","Susy"]
edades = [46,41]

list(zip(nombres,edades))

edadesordenadas = sorted(edades)
edadesordenadas

list(reversed(edadesordenadas))

sum(edades)

max(edades)

min(edades)

sorted (nombres)

list(reversed(nombres))

abs(-5)

pi = 3.141592653589793
round(pi)

round(pi,2)

round(pi,4)

list( map( str.upper, nombres ))

list( map( str.lower, nombres ))

list( filter( lambda x: x >42 , edades ) )

any ([ False, True, False, False ])

any ([ False, 1 == 1, False, False ])

all([ False, True, False, False ])

all ([ False, False, False, False ])

all ([ True, True, True,True ])

nombres.append("Cloe")

nombres

nombres.insert(1,"Yamila")

nombres2 = ["Toxica1","Toxica2"]

nombres.extend(nombres2)

indice = nombres.index("Toxica1")
indice

usuario = {"nombre":"christian", "edad": 45 , "edad":46}

edad = usuario.get("edad",0)
print(edad)

usuario.update({"ciudad": "BUENOS AIRES"})

print(usuario)

claves = usuario.keys();
print(claves)

valores = usuario.values();
print(valores)

items = usuario.items()
print(items)

ciudad = usuario.pop("ciudad")
print(ciudad)

usuario.clear()
print(usuario)

numeros = [1,2,3,4,5,6,7,8,9]
cuadrados = [x**2 for x in numeros]

print (cuadrados)

pares = [x for x in numeros if x % 2 == 0]
print(pares)

etiquetas = ["par" if x % 2 == 0 else "impar" for x in numeros]
print(etiquetas)

productos = {"notebook":1500000, "mouse": 50000, "webcam":200000}
cotizacion = 1500

productosArg = {producto: round(precio/cotizacion,2) for producto, precio in productos.items()}
print(productosArg)

import sys
print(sys.version)

lista = [x for x in range(1000000)]
print(sys.getsizeof(lista))

generador = (x for x in range(1000000))
print(sys.getsizeof(generador))

def contador():
  return 1
  return 2 #codigo inalcanzable

contador()

def contador_yield():
  yield 1
  yield 2
  yield 3

gen = contador_yield()

print(next(gen))
print(next(gen))
print(next(gen))

def fibonacci():
  a, b = 0, 1
  while True:
    yield a
    a, b = b, a + b

gen = fibonacci()

for _ in range(50):
  print(next(gen))

print(next(gen))